services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
  meme-loader:
    depends_on:
      - redis
    build: meme-loader
    volumes:
      - ./meme-loader/src:/app/src
      - ./meme-loader/memes:/app/memes
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  meme-server:
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - meme-loader
    build: meme-server
    volumes:
      - ./meme-server/src:/app/src
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  meme-client:
    ports:
      - "8000:8000"
    depends_on:
      - meme-server
    build: meme-client
    volumes:
      - ./meme-client/src:/app/src
    environment:
      - VITE_MEME_SERVER_PORT=8080
